export const SERVER_PING = 'SERVER_PING'
export const SERVER_ADD_PLAYER = 'SERVER_ADD_PLAYER'
export const SERVER_REMOVE_PLAYER = 'SERVER_REMOVE_PLAYER'
export const SERVER_NUCLEAR_OPTION = 'SERVER_NUCLEAR_OPTION'
export const DELETE_ALL = 'DELETE_ALL'

export const ALERT_POP = 'ALERT_POP'
export const ADD_PLAYER = 'ADD_PLAYER'
export const REMOVE_PLAYER = 'REMOVE_PLAYER'
export const SUBSCRIBE_PLAYER = 'SUBSCRIBE_PLAYER'

export const START_FAILURE = 'START_FAILURE'
export const START_SUCCESS = 'START_SUCCESS'

export const JOIN_GAME = 'JOIN_GAME'
export const NEW_GAME = 'NEW_GAME'
export const LEAVE_GAME = 'LEAVE_GAME'
export const DELETE_GAME = 'DELETE_GAME'
export const UPDATE_GAME = 'UPDATE_GAME'

export const ERROR = 'ERROR'

export const ANNOUNCE_NEW_GAME = 'ANNOUNCE_NEW_GAME'
export const ANNOUNCE_DELETE_IN_PROGRESS_GAME = 'ANNOUNCE_DELETE_IN_PROGRESS_GAME'
export const ANNOUNCE_DELETE_READY_GAME = 'ANNOUNCE_DELETE_READY_GAME'

