export const INVALID_PLAYER_NAME = 'Invalid player name (must be 2-8 alphanumeric characters.'
export const INVALID_ROOM_NAME = 'Invalid room name (must be 2-8 alphanumeric characters.'
export const INVALID_URL_PARAMS = 'Invalid URL parameters. Must match format #username[roomname].'
export const EXISTING_USERNAME = 'This username already exists'
export const GENERIC_ERROR = 'An error occurred'
export const CANNOT_ENTER_GAME_IN_PROGRESS = 'You cannot join a game already in progress.'